### ISSUE TITLE
stickynotes: font and color settings are ignored in GTK+3 build

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-applets#127]
Virtualbox, Debian Jessie, GTK+3 build of MATE 1.9 (all from git master), GTK+ 3.14.5.

Changing any of the font and color settings in both global preferences and note's preferences does nothing.

![bad-sticky-notes](https://cloud.githubusercontent.com/assets/5138986/6000108/c6726d1a-aaea-11e4-8393-8bebd3997303.png)

As you can see on the screenshot, there are different font and background colors and quite large font size selected, but there's no effect. Logging out and back in doesn't help as well.

**Comment by City-busz** [comment]
Font color and bg color are fixed by https://github.com/mate-desktop/mate-applets/commit/6d759e6e81f04059bf17f723a57d58407a5b20e2 and https://github.com/mate-desktop/mate-applets/commit/924bc21d59521dc8955d6d0bafd90b01ef337cd7 , and there is a pull request for font type: https://github.com/mate-desktop/mate-applets/pull/169 .

**Comment by monsta** [comment]
Thanks, #169 merged.
