### ISSUE TITLE
The MATE timer applet does support transparency

### ISSUE THREAD

**Issue by physicsshark** [mate-desktop/mate-applets#136]
I (as well as many other users) enjoy using a panel that is transparent, or partially transparent. 
 All of the other included MATE applets respect my choice of a transparent panel, except the timer applet, which has the background color from my gtk theme.

![screenshot36](https://cloud.githubusercontent.com/assets/9755486/7842067/dbeb55de-046e-11e5-9a15-2e070815b6eb.png)

**Comment by monsta** [comment]
Confirmed, still present in 1.10.

**Comment by NiceandGently** [comment]
With mate gtk3 version i have full transparency for ***all*** applets.
But this depends on theme settings. Menta themes support now full transparency after this commit.
https://github.com/mate-desktop/mate-themes/commit/34d3b36
Unfortunately this isn't possible with gtk2, because theming is very limited.

**Comment by infirit** [comment]
should be fixed with https://github.com/mate-desktop/mate-applets/commit/cff2fddb611ed0d052df970454af1b0bfcfe01b3
