### ISSUE TITLE
GTK3: cpu-freq applet ignores orientation for vertical panels

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-applets#145]
With a vertical panel the text is displayed beside the icon.
It should be under the icon.

**Comment by NiceandGently** [comment]
The panel orientation can be fixed with https://github.com/NiceandGently/mate-applets/commit/6de03b5
But that's pointed out another problems:
On horizontal panels the text isn't visible which can fix with a patch from this forum topic
http://forums.mate-desktop.org/viewtopic.php?f=16&t=3606&sid=f6ee9046fedc50ad7ee91233ee1c2d48
But here the size of the text will be hardcoded.
After that  text and unit displays beside the icon on vertical panels, and under the the icon on vertical panels.
But text and unit has always vertical orientation on vertical and horizontal panels, which is OK for vertical but not for horizontal panels.

**Comment by monsta** [comment]
What's the current status of this? I can't check it as my only GTK+3 installation is in a VM... so cpufreq applet would only show me an empty space :smile:

**Comment by raveit65** [comment]
Time to install gtk3 on baremetal :hamburger:

**Comment by raveit65** [comment]
fixed :smile: 
https://github.com/mate-desktop/mate-applets/commit/300ef94527f603311fed18d7d632740ecf56163c
