### ISSUE TITLE
Cpufreq units are frequency value

### ISSUE THREAD

**Issue by zaps166** [mate-desktop/mate-applets#175]
The cpufreq applet doesn't show units (e.g. GHz) - the units currently are the values. Disabling the units causes a value to disappear.
##

**Comment by monsta** [comment]
Can't reproduce it here - but my applet is built with ```libcpufreq``` support instead of ```libcpupower``` as the latter isn't available in Debian/Ubuntu/Mint. Can you check which one is used in your distro?

**Comment by zaps166** [comment]
I'm using Manjaro, so I think it is the same as in ArchLinux: https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/mate-applets

**Comment by monsta** [comment]
Ok, it seems to use libcpupower since no build flag is set for that and libcpupower is the default one.

For reference, here are screenshots from my system:

![cpufreq-units-on](https://cloud.githubusercontent.com/assets/5138986/12816307/b5654a9a-cb5c-11e5-9db1-c6bc0d36075d.png)

![cpufreq-units-off](https://cloud.githubusercontent.com/assets/5138986/12816325/c769b4ec-cb5c-11e5-8f31-c4df0e5eff0e.png)

As I understand it, in your system the whole text disappears when you turn the units display off?

**Comment by zaps166** [comment]
Yes:

![01](https://cloud.githubusercontent.com/assets/6239090/12816429/c0b7ff2e-cb4c-11e5-8011-0e5ce0ecc4bc.png)
![02](https://cloud.githubusercontent.com/assets/6239090/12816428/c08f592a-cb4c-11e5-86e1-fcc771bd57a7.png)

**Comment by monsta** [comment]
Really weird...

**Comment by zaps166** [comment]
Yes..., but the real problem is here: https://github.com/mate-desktop/mate-applets/issues/173 which makes the applet unusable.

//Anybody knows why the Clock Applet which updates seconds (and Temperature Applet) lock for a while full screen OpenGL application with NVIDIA proprietary + AllowFlipping (NetworkMonitor also does an update very often, but it doesn't interfere with OpenGL...)?

**Comment by zaps166** [comment]
The same reason as in https://github.com/mate-desktop/mate-applets/issues/173 - "intel_pstate" is causing this issue.

**Comment by gav-** [comment]
I have the same issue, but I think it is just because the space for the applet is too narrow and it is cropping the text. Occasionally you can see the first two columns of pixels of the text for the units. In the attached image you can see the start of 'MHz'

![cpufreqmonitor-cropping-units](https://cloud.githubusercontent.com/assets/7419383/12941025/9c9e8eca-d022-11e5-966f-69ec3f01c951.png)

**Comment by monsta** [comment]
@gav-
Well, you can easily test it by creating a new panel and placing applet there (to give it more space) :smile:

**Comment by gav-** [comment]
I have done exactly that. It doesn't matter if it's the only applet on the panel, anywhere on the panel, it has the same effect.

**Comment by hate-m-dollarsign** [comment]
Had the same problem for a few versions. After reading the Mate 1.20 release notes, I got my hopes up this might have been fixed, but no cigar.

The title is also wrong/misleading and should probably be changed. Just like @gav- said, the text is just cropped.

I remember a discussion somewhere else, I don't remember the details and can't seem to find it now, but the general tone was this is much more difficult to fix properly than you might think. Something about vertical panels.

Would be awesome if someone could post a hack/workaround here, like

> width += 20;

or something.

**Comment by lukefromdc** [comment]
Confirmed: I have seen this here with and only with my laptop (intel) and never with my desktop (AMD) machines. The laptop crosses the MHZ/GHZ boundary in unit choice and probably screws this up. This label width code has been such a mess since the first port to GTK3, when it rendered zero width. Probably we are going to have to throw in the towel and set a hardcoded minimum width. Even this has been touchy in the past (I used to do it in the theme for bold text before an issue with that was fixed) as the applet used to somehow get a maximum width

**Comment by lukefromdc** [comment]
I just found that attempting to set a miniumum width for either label or for the box containing them both had zero effect. It seems that on either machines that switch between MHZ and GHZ, maybe only those with certain Intel cpu frequency drivers (of with libcpupower and with the MHZ/GHZ transition) that might be slow to first report results, that the frequency label is not getting added. Then, the applet's maximum width is getting computed for the case of having only one label plus the image packed into the applet. That's my guess.

**Comment by lukefromdc** [comment]
Try
https://github.com/mate-desktop/mate-applets/pull/320
which fixed this in a laptop of mine with the same problem.

**Comment by hate-m-dollarsign** [comment]
I just tried it out on Mint 19, works like a charm! Thanks Luke, great job!

**Comment by lukefromdc** [comment]
I am proposing we cherrypick https://github.com/mate-desktop/mate-applets/pull/320 to 1.20 so people running their distro's packages can get it

**Comment by raveit65** [comment]
@lukefromdc 
Yes this is a bug fix, feel free to cherry-pick this one.

**Comment by lukefromdc** [comment]
Done in 
https://github.com/mate-desktop/mate-applets/commit/0e139588d9b09bd3871848a617a107b3e4a3940b
https://github.com/mate-desktop/mate-applets/commit/704fe9863ff03b09271f3055b101300a2b9135f9
and
https://github.com/mate-desktop/mate-applets/commit/0a00b7cd3601a190d464dd52beff9df7cfb1ff0f

**Comment by hate-m-dollarsign** [comment]
@lukefromdc did you check out bountysource for this bug? https://www.bountysource.com/issues/29483543-cpufreq-units-are-frequency-value
There are $5 for you ;)

**Comment by lukefromdc** [comment]
Unfortunately, Boutysource only pays out cashouts by Paypal right now, and is considering Bitcoin. I have no Paypal account and no connection to online banking, thus no way to cash out bounty claims. They used to offer physical checks but stopped after a change of ownership. After two successful collections of earlier bounties, I ended up refunding my last attempt back to the poster when Bountysource refused to make an exception.

**Comment by hate-m-dollarsign** [comment]
Aw, bummer. Sorry, man!
If you can PM me your IBAN somehow, I will send you 5 bucks ;)

**Comment by lukefromdc** [comment]
I don't know how to do a PM here, and I don't think small consumer accounts in US banks here even have IBAN numbers. They could not help when this came up with another bounty poster. Don't worry about the money, an hour to get to and deal with the bank over a $5 bounty pays only $5 an hour.

**Comment by lukefromdc** [comment]
You will probably need to pull down the bounty in some way as this is fixed however.
