### ISSUE TITLE
Mate Netspeed 1.8.0 display bits

### ISSUE THREAD

**Issue by alan-camilo** [mate-desktop/mate-applets#200]
The bug is observed in the french version of the applet.
In the settings, when we choose "display bits instead of octets", the applet displays the terms "b/s", "kb/s" and "mo/s" instead of "mb/s".
![selection_004](https://cloud.githubusercontent.com/assets/8865038/17223972/384f04ba-54ff-11e6-8572-cf227752dbaf.jpg)

**Comment by raveit65** [comment]
Mate-1.8 is obsolete since a long time, current supported version is 1.14, here netspeed is part of mat-applets.
Sorry, we are a very small team an we can't support such old mate-versions.
I assume that you're are using debian, please file out a report there and ask maintainer to back port translation updates.
From my point of view  (fedora maintainer) you're are a victim of debians update politic ;)
stable= a lot of issues will never fixed.

**Comment by alan-camilo** [comment]
Actually, I'm running Ubuntu mate LTS 14.04, that is why my version is completely obsolete :)
I think my issue will be solved when I upgrade to 16.04.1 ubuntu version, it's running mate 1.14.
And on my pov, I'm totally ok with the debian or ubuntu LTS politics and I prefer stability. So, that kind of little bug doesn't upset me.
