### ISSUE TITLE
[Patch Included] mateweather: suncalc_timeout_cb randomly gets called multiple times

### ISSUE THREAD

**Issue by ZeGentzy** [mate-desktop/mate-applets#231]
This causes notification spam (if they are enabled) according to: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823790

A solution is to simply not update on sunrise/sunset (why would you anyways?), here is a patch which does this: https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=823790;filename=bug823790.patch;msg=40

**Comment by raveit65** [comment]
fixed with
https://github.com/mate-desktop/libmateweather/commit/97326e615fffaef92669dbe82c8955c2c2e2edda
https://github.com/mate-desktop/libmateweather/commit/c307e7c9ee89e4ac17cc2bb2aa1e245d766cbc5e
https://github.com/mate-desktop/mate-applets/commit/109a7fa77bb4745524eca8a0735b210b55b81fe0
https://github.com/mate-desktop/mate-applets/commit/dc71847a5490abad09ef0b4955b5461d8e66ed3f

**Comment by raveit65** [comment]
Fixed libmateweather-1.19.1 and mate-applets-1.19.0 are released.
