### ISSUE TITLE
Current weather not properly shown in tooltip

### ISSUE THREAD

**Issue by assen-totin** [mate-desktop/mate-applets#289]
#### Expected behaviour
When the mouse is pointed at the icon of the current weather, the tooltip should display the current weather. 

#### Actual behaviour
Sometimes instead of the current weather, the tooltip shows the text for the neighbouring calendar instead. There is no obvious dependency when this error happens and when the weather is shown properly; however, this happens often enough to get annoying. As an observation, when the error occurs, there is a brief flicker of the tooltip - as if the proper weather tooltip is shown, then immediately removed and the wrong one is displayed. 

Here is what the error looks like: 
http://www.zavedil.com/a/applet.png

#### Steps to reproduce the behaviour
Point your mouse at the icon weather and keep it there until the tooltip is shown.

#### MATE general version
1.18

#### Package version
mate-applets-1.18.2-2.fc26.x86_64

#### Linux Distribution
Fedora 25, Fedora 26. 

#### Link to downstream report of your Distribution
None.

**Comment by monsta** [comment]
> the tooltip shows the text for the neighbouring calendar instead

It happens when current weather can't be retrieved. The applet itself shows previously retrieved weather at that time. If you restart the panel, there will be empty space instead of weather, as the applet will be forced to refresh it, but won't be able to get it. I saw it a lot last week - probably some problem at my local weather stations.

The clock applet is actually from mate-panel repo. We can't move bug reports between repos, so please file a new report there.
