### ISSUE TITLE
Travis CI ubuntu build fails

### ISSUE THREAD

**Issue by shlyakpavel** [mate-desktop/mate-applets#416]
#### Expected behaviour
Every PR is tested on Travis CI

#### Actual behaviour
Ubuntu instance reports build failure

#### Steps to reproduce the behaviour
1. Leave PR
2. Check Travis

#### MATE general version
upstream master

**Comment by raveit65** [comment]
Problem is well known and needs to be fixed by ubuntu kernel maintaner.
Until now @flexiondotorg patched official ubuntu build.
It's really time to switch from cpufreq (unmantained in ubuntu) to cpupower from kernel.
All other main distros use that since years.
I don't think we need a new report for it.
See here for references.
https://github.com/mate-desktop/mate-applets/pull/413#issuecomment-520819712

**Comment by raveit65** [comment]
PS: ignore ubuntu travis build for the moment and use others to take a look in build logs ;)
